SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_line_types;
DROP TABLE IF EXISTS user_lines;
DROP TABLE IF EXISTS sections;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS sections;

CREATE TABLE users (
	id       INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name     VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id)
);

CREATE TABLE user_line_types (
	id      INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name    VARCHAR(255) NOT NULL,
	visible BOOLEAN NOT NULL DEFAULT 1,

	PRIMARY KEY (id)
);

INSERT INTO user_line_types(name) values ('email');

CREATE TABLE user_lines (
	id      INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	user    INTEGER UNSIGNED NOT NULL,
	type    INTEGER UNSIGNED NOT NULL,
	value   VARCHAR(255) NOT NULL,
	visible BOOLEAN NOT NULL DEFAULT 1,

	PRIMARY KEY (id),
	FOREIGN KEY (user) REFERENCES users(id),
	FOREIGN KEY (type) REFERENCES user_line_types(id)
);

CREATE TABLE sections (
	id          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name        VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	banner      VARCHAR(255) NOT NULL,

	PRIMARY KEY (id),
	UNIQUE KEY (name)
);

CREATE TABLE posts (
	id      INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	user    INTEGER UNSIGNED NOT NULL,
	section INTEGER UNSIGNED NOT NULL,
	title   VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	type    INTEGER UNSIGNED NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	visible BOOLEAN NOT NULL DEFAULT 1,

	PRIMARY KEY (id),
	FOREIGN KEY (user) REFERENCES users(id),
	FOREIGN KEY (section) REFERENCES sections(id)
);

CREATE TABLE comments (
	id      INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	post    INTEGER UNSIGNED NOT NULL,

	depth   INTEGER UNSIGNED NOT NULL DEFAULT 0,
	lineage VARCHAR(255) NOT NULL DEFAULT '',

	user    INTEGER UNSIGNED NOT NULL,
	content VARCHAR(255) NOT NULL,
	parent  INTEGER UNSIGNED,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id),
	FOREIGN KEY (post) REFERENCES posts(id),
	FOREIGN KEY (parent) REFERENCES comments(id)
);

SET FOREIGN_KEY_CHECKS=1;

